name: CI - Build Java 21

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Baixar cÃ³digo do repositÃ³rio
        uses: actions/checkout@v7

      - name: Configurar Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilar
        run: mvn -B clean compile

      - name: Executar testes
        run: mvn -B test

      - name: Gerar JAR
        run: mvn -B -DskipTests package

      - name: Disponibilizar artefato
        uses: actions/upload-artifact@v7
        with:
          name: multiplicador
          path: target/multiplicador-0.0.1-SNAPSHOT.jar
          if-no-files-found: error
